# Generated by Django 4.0.6 on 2022-07-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='show_answer',
            field=models.BooleanField(default=False),
        ),
    ]
