# Generated by Django 4.0.6 on 2022-07-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_show_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='show_answer',
        ),
    ]
