# Generated by Django 4.0.6 on 2022-08-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_quiz_author_remove_quiz_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startquiz',
            name='finished_at',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=2048),
        ),
    ]
