# Generated by Django 4.0.6 on 2022-08-03 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_userquiz_rename_questions_questionoption_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquizanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='userquizanswer',
            name='option_ids',
        ),
        migrations.AddField(
            model_name='userquizanswer',
            name='response',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='response', to='quiz.questionoption'),
            preserve_default=False,
        ),
    ]
