# Generated by Django 4.0.6 on 2022-08-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_userquizanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userquizanswer',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.questionoption'),
        ),
    ]
