# Generated by Django 4.0.6 on 2022-08-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_userquizanswer_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizAnswerStats',
        ),
    ]
