# Generated by Django 4.0.6 on 2022-08-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_delete_quizanswerstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquizanswer',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='userquizanswer',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_response', to='quiz.questionoption'),
        ),
        migrations.AlterField(
            model_name='userquizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_question', to='quiz.question'),
        ),
    ]
